line-length = 88
target-version = "py311"

exclude = [
    ".venv",
    "venv",
    "migrations",
    "__pycache__",
]

[lint]
select = [
    "E",
    "W",
    "F",
    "I",
    "DJ",
]
ignore = [
    "E501",
]